[package]
name = "security-english-words-for-anki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
csv = "1.1.6"
genanki-rs = "0.1.3"
